version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.mariadb.yml
      service: mariadb

  diver-api:
    extends:
      file: ./compose/compose.driver-api.yml
      service: driver-api

  car-api:
    extends:
      file: ./compose/compose.car-api.yml
      service: car-api
