version: '3.8'

services:
  race-api:
    container_name: race-manager-race-api
    image: node:16
    working_dir: /app
    volumes:
      - ../api/race-api:/app
      - ../certs:/app/certs
    environment:
      - API_URL=race-api:7000
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mariadb:3306/race
      - SECRET_KEY=${APP_SECRET_KEY}
      - AUTH_KEY=/certs/race-api-key.pem
      - AUTH_CERT=/certs/race-api.pem
    ports:
      - 7000:7000
    stdin_open: true
    command: npm run start:${APP_MOD}
