version: '3.8'

services:
  driver-api:
    container_name: race-manager-driver-api
    image: node:16
    working_dir: /app
    volumes:
      - ../api/driver-api:/app
      - ../certs:/app/certs
    environment:
      - API_URL=driver-api:7000
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mariadb:3306/driver
      - SECRET_KEY=${APP_SECRET_KEY}
      - AUTH_KEY=/certs/driver-api-key.pem
      - AUTH_CERT=/certs/driver-api.pem
    ports:
      - 7000:7000
    stdin_open: true
    command: npm run start:${APP_MOD}
