version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "6033:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}