version: '3.8'

services:
  car-api:
    container_name: race-manager-car-api
    image: node:16
    working_dir: /app
    volumes:
      - ../api/car-api:/app
      - ../certs:/app/certs
    environment:
      - API_URL=race-manager-car-api:${CAR_API_PORT}
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mariadb:3306/car
      - SECRET_KEY=${APP_SECRET_KEY}
      - AUTH_KEY=/certs/car-api-key.pem
      - AUTH_CERT=/certs/car-api.pem
    ports:
      - ${CAR_API_PORT}:${CAR_API_PORT}
    stdin_open: true
    command: npm run start:${APP_MOD}
